version: '3.8'

services:
  search-service:
    # Build the image from the Dockerfile in the current directory
    build: .
    # Map host port 8000 to container port 8000
    ports:
      - "8000:8000"
    # Mount the local 'app' directory into the container for live reloading
    # This is great for development
    volumes:
      - ./app:/app/app
    # Set environment variable for immediate log output
    environment:
      - PYTHONUNBUFFERED=1
    # Override the Dockerfile's CMD to enable --reload for development
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload