# docker-compose.yml
services:
  seeder-worker:
    build: .
    environment:
      PYTHONUNBUFFERED: 1
      DATABASE_URL: ${DATABASE_URL}
      KAFKA_BROKER_URL: ${KAFKA_BROKER_URL}
      MODEL_READY_TOPIC: ${MODEL_READY_TOPIC}
  data-collector:
    build: .
    environment:
      SERVICE_NAME: "data-collector"
      PYTHONUNBUFFERED: 1
      DATABASE_URL: ${DATABASE_URL}
      KAFKA_BROKER_URL: ${KAFKA_BROKER_URL}

  suggestion-worker:
    build: .
    environment:
      SERVICE_NAME: "suggestion-worker"
      PYTHONUNBUFFERED: 1
      DATABASE_URL: ${DATABASE_URL}
      KAFKA_BROKER_URL: ${KAFKA_BROKER_URL}
      SUGGESTION_REQUESTS_TOPIC: ${SUGGESTION_REQUESTS_TOPIC}
      SUGGESTION_RESULTS_TOPIC: ${SUGGESTION_RESULTS_TOPIC}

  search-service:
    build: .
    environment:
      SERVICE_NAME: "search-service"
      PYTHONUNBUFFERED: 1
      DATABASE_URL: ${DATABASE_URL}
      KAFKA_BROKER_URL: ${KAFKA_BROKER_URL}
      SEARCH_REQUESTS_TOPIC: ${SEARCH_REQUESTS_TOPIC}
      SEARCH_RESULTS_TOPIC: ${SEARCH_RESULTS_TOPIC}
      SEARCH_LOGGING_TOPIC: ${SEARCH_LOGGING_TOPIC}