# docker-compose.yml

services:
  postgres:
    image: ankane/pgvector:latest
    environment:
      # These now read from the .env file
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432" # Use the port from .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./DDL.txt:/docker-entrypoint-initdb.d/01-schema.sql

  search-service:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: